import Head from "next/head";
import Image from "next/image";
import React, { useEffect, useState } from "react";
import { FlexBox } from "../Components/GlobalComponents";
import styles from "../styles/Home.module.css";
import Calculator from "./Calculator";

function Home() {
  // const [name, setName] = useState("");
  // const [password, setPassword] = useState("");
  // console.log(name, password)
  return (
    <div className={styles.container}>
      <Head>
        <title>Precice Set</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Calculator/>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export default Home;
